### ISSUE TITLE
Commit policy and reproducible builds.

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/main#2]
It is a  well established policy in both programming and documentation that generated files should not be part of the git repo. The repo should just contain the sources (basically  adoc, yml  and image files) and no html files. There are multiple reasons for this, I'll leave them out for now.

However, to be able to do this we must have reproducible builds. That is, when two users builds the documentation from a given commit they should get the same thing. More specifically, if we checkout a specific commit in this main project we should always get the same result -- it should not depend on if there are changes in plugins or development manual.

I'm not quite sure about the current situation. I will try to dive into this, and will report more later.  Will work with the now existing sources in this project.

Process issues like these *are* sort of boring, but IMHO we need to sort this out to get not just a descent manual but also a working (and improved) process for manual maintenance.

**Comment by Rasbats** [comment]
Ok ... but for test purposes I need to build and see results. Using sources generated from the sources.state file means that all the plugin manuals are built from reproducible commits. 

>generated files should not be part of the git repo

How can github pages operate without docs being generated?

I have been building locally with a clone and the product works fine. Perhaps best to follow this path and delete the docs folder from the plugins repo.

**Comment by leamas** [comment]
> Ok ... but for test purposes I need to build and see results. Using sources generated from the sources.state file means that all the plugin manuals are built from reproducible commits.

Of course, and it must always be possible (and easy!) to make a new commit. A new commit means that we build something different.

Looking at it more practical: We continue to work, making changes and commits, each commit means a new version. But, at a certain point we make a release. More practically, this means that we tag the sources. And for things to be sane, anyone who checks out that tag should be able to build exactly the same manual. 

Another POV is that if we want to fix an error in the manual we must be able to checkout the correct sources, apply a simple patch and rebuild the manual. If it's reproducible, the new manual will include only the change caused by the patch. If not, the new manual will contain all sorts of changes which  is a maintenance nightmake.

**Comment by leamas** [comment]
> How can github pages operate without docs being generated?

Oops, that one... I need to look into that. Back later

**Comment by Rasbats** [comment]
Not sure where main repo is heading. What is the reason for having the plugins repo or the development repo?

**Comment by leamas** [comment]
> What is the reason for having the plugins repo or the development repo?

Only to be able to build them separately, and perhaps just to divide the big beast into manageable pieces.

> Not sure where main repo is heading

Working on it right now... The "don't check in the html files" part is fixed.

**Comment by leamas** [comment]
OK, I see a problem how to use source-state.sh in combination with the modules used to build the site in github actions. I'm on it,  but not more today -- going in circles.

**Comment by leamas** [comment]
I have pushed some commits on main/main. I think the basic pieces now are in place.

The generated files in docs/ are not part of the repo. Still, github pages needs them checked in. This is handled by a working branch *gh-pages*.  A push to the main branch does not trigger any build of the website. OTOH, `git push -f origin main:gh-pages` creates a new build which ends up at github.io. The gh-pages branch is thus basically just a temporary, it has no use after publishing the build.

The files under sources/ are also not part of the repo.  While building locally, they are handled manually using source-state.sh. Note that it's not necessary to just use this script. If you wan to use a specific version of for example a plugin, just go to sources/plugin and checkout this version. `source-state.sh save`will then record this version in sources.state, and restore it when doing `source-state.sh restore`.

When the github actions workflow runs, it does a `source-state.sh restore` which populates the sources directory before the build.

**Comment by leamas** [comment]
Revisited:

> What is the reason for having the plugins repo or the development repo?

One important reason is to have the local build. Building and publishing the complete manual now takes about 5 minutes, which is long to wait for simple fixes. We should have well-defined local build scripts in the developer and plugin projects so it's simple to check things.

However, *publishing* from the plugins or development project is complicated since it will overwrite the overall manual. Need to read up to see what's possible here, but this is perhaps not the most urgent task (?)

**Comment by leamas** [comment]
As I see it, the reproducible part is now fixed in the main repo. The job on github.io rebuilds the docs completely without using any checked-in, generated files. Or?

Are we happy with the separate builds possible in the developer and plugins project? Or is it too large an overhead for the benefits?

**Comment by Rasbats** [comment]
>Are we happy with the separate builds possible in the developer and plugins project? 

Happy to be able to make my own builds with plugins repo.

I am seeing a lot of duplication in the main repo. main/opencpn-plugins-manual and also main/manual, main/manual-beta. This seems to carry over into the files in gh-pages.

**Comment by leamas** [comment]
OK. Then  I suggest that we close this issue. And spend whatever time we have on https://github.com/opencpn-manuals/plugins/issues/4. OK?

**Comment by Rasbats** [comment]
Agreed. I will remove plugins/docs as a start.

**Comment by leamas** [comment]
Right. Let's close this
