### ISSUE TITLE
Appendix page - where are the commit details coming from?

### ISSUE THREAD

**Issue by Rasbats** [opencpn-manuals/main#29]
Using ais-vd_pi as an example.
Commit [https://github.com/Hakansv/ais-vd_pi/commit/195dab749983a6fa4fc2f91899293ade1eba5555](https://github.com/Hakansv/ais-vd_pi/commit/195dab749983a6fa4fc2f91899293ade1eba5555) was the latest.
Appears in the appendix as commit fb2c7d0 with a strange date.

**Comment by leamas** [comment]
The details are picked up by the src-list.js script which generates the directory. The basic flow:
  - Antora looks in site.yml and downloads all sources to "hidden" directory
  - During the build, it first collects all sources.
  - At this point, the src-list.js is invoked, listing the used sources including the last commit etc.

Looking at last build, the commit description looks fine (version 1.7.7), so also the commit date.  However,  the commit hash is plain wrong. Will look into it.

**Comment by leamas** [comment]
Fixed. Thanks for spotting it!
